### PR TITLE
Allow for MOTO via WPF

### PR DESCRIPTION
**Pull request by mrploddy1981**
Small additions to the WPF Create request to allow for WPF to process MOTO transactions

* Adds MotoAttributes trait to WPF Create
* Adds MOTO transaction type attribute to addTransactionType method

-----------------

Before merging the PR make sure the following are checked:

* [ ] [Good commit messages][1] are used.
* [ ] Commit message starts with `{f|b}{year}{month}{day}{num}`, e.g. f2016071101
* [ ] Necessary specs are added.
* [ ] All specs are passing.
* [ ] The **PHP** code style complies with the [PSR-2][2] recommendation
* [ ] All automated or manual PR comments are resolved or proper explanation is included for the given change
* [ ] The PR relates to **only** one subject with a clear title

[1]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[2]: http://www.php-fig.org/psr/psr-2/

### CODE REVIEW

**Comment by dyd** [comment]
Hello @mrploddy1981,

Thank you very much for the suggested feature. We will investigate if the `moto` attribute is appropriate inside the WPF parameters structure.
You can attach the `moto` attribute for a specific Transaction Type by adding a custom attribute to it with this sample:

```
->addTransactionType(
    'authorize',
    [
        'moto' => true
    ]
)
```
A full list of the custom attributes can be found here: https://emerchantpay.github.io/gateway-api-docs/?shell#wpf-transaction-types

**Comment by mrploddy1981** [comment]
@dyd 

I'm currently doing a integration and had a requirement to be able to process MOTO payments using the WPF. This is because I didn't want to have to go to SAQ-D level compliance for server 2 server comms. 

This is because it's for a travel booking / reservation system where our clients want to be able to do MOTO payments from within our system without having to log in to your merchant back end to process the MOTO payment (eg they have a client on the phone and they want to make a phone payment)

I tried your suggestion and it does actually work so in fact the only thing that's needed to enable MOTO for WPF is to add the MotoAttributes to the use statement. The modifications to the addTransactionType are not required. 

This has been tested and confirmed to be working perfectly by support - if you want more information please ask Yordan  / Alejandros in support as they are who I'm currently dealing with.

**Comment by mrploddy1981** [comment]
@dyd Have updated my pull reques tto remove the unecessary code based on your suggestion.

**Comment by dyd** [comment]
Hello @mrploddy1981,

We discussed the case with the assigned people from Tech Support.
You can use the suggested way of assigning a custom attribute to the specific transaction type inside the WPF -> https://github.com/GenesisGateway/genesis_php/pull/14#issuecomment-1006452442

I hope this helps. I am closing the PR. No changes are required.

**Pull request closed without merging**
